# Generated by Django 5.0 on 2024-02-01 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=256)),
                ('product_photo', models.ImageField(upload_to='custom_orders_photos')),
                ('product_size', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stripe_custom_order_price_id', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'В обработке'), (1, 'Ожидает оплаты'), (2, 'Оплачен'), (3, 'В пути'), (4, 'Доставлен')], default=0)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'custom order',
                'verbose_name_plural': 'custom orders',
            },
        ),
    ]
