# Generated by Django 5.0 on 2024-02-04 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_customorder'),
        ('products', '0006_remove_product_verified_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customorder',
            name='price',
        ),
        migrations.RemoveField(
            model_name='customorder',
            name='status',
        ),
        migrations.RemoveField(
            model_name='customorder',
            name='stripe_custom_order_price_id',
        ),
        migrations.AddField(
            model_name='customorder',
            name='product',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'Индивидуальный заказ'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
