# Generated by Django 5.0 on 2024-02-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_customorder_price_remove_customorder_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customorder',
            name='product_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
