# Generated by Django 5.0 on 2024-02-05 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_customorder_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customorder',
            options={'verbose_name': 'custom order', 'verbose_name_plural': 'Индивидуальные заявки'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Заказы'},
        ),
    ]
