# Generated by Django 5.0 on 2024-02-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_boxberry_delivery',
            field=models.BooleanField(default=False, verbose_name='Доставка Boxberry'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_cdek_delivery',
            field=models.BooleanField(default=False, verbose_name='Доставка СДЭК'),
        ),
    ]
