# Generated by Django 5.0 on 2024-01-31 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='verified_address',
            field=models.BooleanField(default=False),
        ),
    ]
