# Generated by Django 5.0 on 2024-02-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_verified_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_no_verified_email',
            field=models.BooleanField(default=False),
        ),
    ]
