# Generated by Django 5.0 on 2024-02-05 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_users_is_no_verified_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='is_no_verified_email',
            new_name='unverified_email',
        ),
    ]
