# Generated by Django 5.0 on 2024-02-05 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_is_no_verified_email_users_unverified_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='unverified_email',
            new_name='unverified_address',
        ),
    ]
