# Generated by Django 5.0 on 2024-02-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_users_fio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='fio',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
