# Generated by Django 5.0 on 2024-02-15 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_users_fio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='unverified_address',
        ),
        migrations.RemoveField(
            model_name='users',
            name='verified_address',
        ),
    ]
