# Generated by Django 5.0 on 2024-01-31 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_stripe_product_price_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='stripe_size_price_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
