# Generated by Django 5.0 on 2024-01-31 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_size_stripe_size_price_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='verified_address',
            field=models.BooleanField(default=False),
        ),
    ]
