# Generated by Django 5.0 on 2024-01-05 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_basket_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Slider image', 'verbose_name_plural': 'Slider image'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'size to product', 'verbose_name_plural': 'size to products'},
        ),
    ]
