# Generated by Django 5.0 on 2024-01-31 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_verified_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='verified_address',
        ),
    ]
