# Generated by Django 5.0 on 2024-01-09 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_exchangerate_tariff_product_tariff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.tariff'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productcategory'),
        ),
    ]
