# Generated by Django 5.0 on 2024-02-05 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_externalimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangerate',
            options={'verbose_name_plural': 'Курс валюты'},
        ),
        migrations.AlterModelOptions(
            name='externalimage',
            options={'verbose_name_plural': 'Постеры'},
        ),
        migrations.AlterModelOptions(
            name='tariff',
            options={'verbose_name_plural': 'Тарифы'},
        ),
    ]
