# Generated by Django 5.0 on 2024-01-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_tariff_alter_tariff_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
