# Generated by Django 5.0 on 2024-01-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_size_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerate',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='rate',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
